/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chowd
 */

import javax.swing.*;
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        ButtonGroup g = new ButtonGroup();
        g.add(listRButton);
        g.add(searchRButton);
        g.add(quitRButton);
        srchTxtFld.setEnabled(false);
        typeBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        listRButton = new javax.swing.JRadioButton();
        searchRButton = new javax.swing.JRadioButton();
        srchTxtFld = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        typeBox = new javax.swing.JTextField();
        quitRButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOP Assignment 2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listRButton.setText("List Accounts");
        listRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRButtonActionPerformed(evt);
            }
        });

        searchRButton.setText("Search...");
        searchRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRButtonActionPerformed(evt);
            }
        });

        srchTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchTxtFldActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        quitRButton.setText("Quit");
        quitRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitRButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Account Type: (c or s)");

        jLabel2.setText("Enter Name to search for:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchRButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quitRButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listRButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(srchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listRButton)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchRButton)
                    .addComponent(srchTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitRButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srchTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchTxtFldActionPerformed

    private void listRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRButtonActionPerformed
        // TODO add your handling code here:
        srchTxtFld.setEnabled(false);
        typeBox.setEnabled(true);
    }//GEN-LAST:event_listRButtonActionPerformed

    private void searchRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRButtonActionPerformed
        // TODO add your handling code here:
        srchTxtFld.setEnabled(true);
        typeBox.setEnabled(false);
    }//GEN-LAST:event_searchRButtonActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //SavingAccount test = new SavingAccount("name", 's', 0.0, 0.0);
        SavingAccount[] barr = new SavingAccount[50];
        
        //String f = "TTU10";
        //JOptionPane.showMessageDialog(null, f.compareTo("TTU9"));
        
        for(int i = 0; i < 50; i ++)
        {
            String n = "TTU" + (i+1);
            char t;
            if(i % 2 == 1)
                t = 's';
            else
                t = 'c';
            double b = i;
            double r = i;
            barr[i] = new SavingAccount(n,t,b,r);
        }
        if(listRButton.isSelected()) // Case for listing based on 
        {
            String typeIn = typeBox.getText();
            char type = typeIn.charAt(0);
            barr = SavingAccount.sortByName(barr, 0, type);
            String s = "";
            
            //JOptionPane.showMessageDialog(null, "The sorted account list is:" + s);
            for(int i = 0; i < 50; i++)
            {
                if(barr[i].getType()== type)
                {
                    s += "Name: " + barr[i].getName() + " ID: " + barr[i].getId() + " Type: "+ barr[i].getType() + " Balance: " + barr[i].getBalance() + " Rate: " + barr[i].getRate() + "     ";
                    if(i % 3 == 0)
                        s+="\n";
                }
                
                //JOptionPane.showMessageDialog(null, "The sorted account list is:" + s);
            }
            JOptionPane.showMessageDialog(null, "The sorted account list is:" + s);
        }
        
        if(searchRButton.isSelected())
        {
            String n = srchTxtFld.getText();
            //JOptionPane.showMessageDialog(null, n);
            SavingAccount s = SavingAccount.search(n,barr);
            if(s != null)
            {
                JOptionPane.showMessageDialog(null, "Account Details:\nName:" + s.getName() + " ID: " + s.getId() + " Balance: " + s.getBalance() + " Rate: " + s.getRate());
            }
            else
                JOptionPane.showMessageDialog(null, "That name is not in the stored values.");
        }
        
        if(quitRButton.isSelected())
        {
            dispose();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void quitRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitRButtonActionPerformed
        // TODO add your handling code here:
        typeBox.setEnabled(false);
        srchTxtFld.setEnabled(false);
    }//GEN-LAST:event_quitRButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton listRButton;
    private javax.swing.JRadioButton quitRButton;
    private javax.swing.JRadioButton searchRButton;
    private javax.swing.JTextField srchTxtFld;
    private javax.swing.JTextField typeBox;
    // End of variables declaration//GEN-END:variables
}


